### ISSUE TITLE
Create checkout session with custom id doesn't correspond to a firebase auth user

### ISSUE THREAD

**Issue by RodanoJ** [stripe/stripe-firebase-extensions#101]
When checkout session is created under a customer/{id}/checkout_sessions where the {id} doesn't correspond to a firebase auth uid, the following error message is generated in the document. 

"There is no user record corresponding to the provided identifier."

My thought was to create a "customer" that was independent from a single firebase auth user which would represent a company/team/organization... however the extension appears to require the customer to have the same key as a auth uid. Is this by design, or is there some workaround so that the stripe customer and customer document in firestore can be independent of a single user.

**Comment by thorsten-stripe** [comment]
@RodanoJ I'm afraid this is by design. We need a 1-1 mapping of Firebase UID to stripe customer ID to facilitate authentication for access to the Stripe customer portal.

What you can do is track your teams in a separate collection and only allow one team admin. The team admin is a user in the customers collection. You then write an additional Cloud Function that triggers anytime a subscription on a customer changes and then check if they are a team admin and if so set access for all team members in your separate teams collection etc.
