### ISSUE TITLE
manageSubscriptionStatusChange activated twice after subscribing

### ISSUE THREAD

**Issue by koenmtb1** [stripe/stripe-firebase-extensions#146]
# Bug report

firestore-stripe-subscriptions

## Describe the bug

The `manageSubscriptionStatusChange` function is activated twice when someone subscribes, this doesn't seem necessary to me. It happens once on the `customer.subscription.created` event and once for the `checkout.session.completed`. If I'm thinking correctly here the `checkout.session.completed` event is actually not necessary for everything to work?

## To Reproduce

No steps necessary, see logs that proof that it activates the function twice.

## Expected behavior

Remove the `checkout.session.completed` event entirely, or give guidance on why its activated.

**Comment by thorsten-stripe** [comment]
@koenmtb1 Stripe Checkout waits for `checkout.session.completed` to be processed by the webhook handler before redirecting back to your `return_url`. This way you know for sure that the subscription (and optionally the custom claim) has been created in Cloud Firestore by the time your user returns back to your app, making sure they will see their subscription status reflected at that point.

Therefore if you use Stripe Checkout, you will likely want to listen to `checkout.session.completed` but you could remove `customer.subscription.created` from your list of events in your Stripe Dashboard.

However, `customer.subscription.created` is needed if you create the subscription through different means than Stripe Checkout, e.g. if you create subscriptions in your Stripe Dashboard, or directly via the Stripe API. 

But depending on your integration, you can potentially remove one of the events from your list.

**Comment by ixartz** [comment]
@thorsten-stripe Thank you for your response, I also understand a little bit more.

But I have another question about this. You told use we shouldn't remove `customer.subscription.created` because we can create subscription in Dashboard or directly via Stripe API.

What about the other way around? Why not removing `checkout.session.completed`?
I don't see any use case when `checkout.session.completed` is needed for subscription.

We can use only `customer.subscription.created`, `customer.subscription.updated` and `customer.subscription.deleted`.

**Comment by thorsten-stripe** [comment]
The reason you want to use `checkout.session.completed` is that Stripe Checkout waits for the `checkout.session.completed` webhook event to be processed before redirecting your customer back to your page. This means that we are sure that by the time your customer lands back on your page, we have updated your Cloud Firestore and custom claims. This isn't the case for `customer.subscription.created`, so it could happen that your customer lands back on your page but their subscription status has not yet been synced. Hope that makes sense.

**Comment by ixartz** [comment]
Thank you for your response.
Now, it totally makes sense for me.

**Comment by ixartz** [comment]
@thorsten-stripe I've another question to these events. At the end of `customer.subscription.created`, the code run the following code: https://github.com/stripe/stripe-firebase-extensions/blob/114d09c6f4d3310acd3cc67702991ad02808047d/firestore-stripe-subscriptions/functions/src/index.ts#L436

If I understand correctly, it updates the customer personal information provided during checkout session, right? For example during checkout, the customer can indicates his name for his payment and it also update his own customer information by adding his name. Otherwise, the customer name stays empty.

My question is why we don't use the following attribute: https://stripe.com/docs/api/checkout/sessions/create

Is it the same thing?
