### ISSUE TITLE
Bug Report: Inconsistency in how Webhook function handles one-time pricing

### ISSUE THREAD

**Issue by justin-elias** [stripe/stripe-firebase-extensions#17]
# Bug report

firestore-stripe-subscriptions

## Describe the bug

The webhook function will consume a _product.create_ or _product.update_ request but disregards any prices marked as _one-time_ because the _interval_ is set to **null**. Yet will send a **400** response for any _price.create_ or _price.update_ requests. 

This creates unpriced products in the firestore database with no way to reconcile them with the Stripe catalog.

### Case 1
1. Go to the Stripe Dashboard
2. Create a product with a one-time price
3. Go to Firestore dashboard
4. See that product was created without a price sub-document

### Case 2
1. Go to the Stripe Dashboard
2. Create or update a price on a product to be a one-time price
3. Go to Stripe Webhook Monitor
4. See that the request failed

## Expected behavior

Consistency in how the extension handles one-time prices on products. EIther it should create and update the price document in Firestore, or it should refuse product requests that contain only one-time prices.

**Comment by Bickio** [comment]
I have also experienced this. It looks like a bug in the insertPriceRecord function. It's reading price.recurring.interval regardless of whether price.recurring is null.
This causes the cloud function to fail, and therefore the websocket trigger fails also.

**Comment by thorsten-stripe** [comment]
Thanks for reporting this! Since the extension only supports Checkout for recurring prices, I'd say we should ignore one-time prices.

Some questions: whats your use-case for having both recurring and one-time prices on the same Stripe account? In what context do you use the one-time prices, and would there be any benefit of also syncing the one-time prices to Firestore, even if you can't use them with the extension?

**Comment by Bickio** [comment]
Hi,

Thanks for your reply. Yes, I realized afterwards that it was only designed
for recurring billing. My app only needs one time billing so it's not a big
issue.

I was hoping that the extension would support this, but now I realize that
it's not supported I will just use the stripe api directly.

Thanks for your help!
Bickio

**Comment by thorsten-stripe** [comment]
@Bickio yes, the real power of this extension lies in the syncing of subscription status with Cloud Firestore and Firebase Authentication. For one-time payments you might find https://github.com/firebase/functions-samples/tree/master/stripe helpful.

**Comment by justin-elias** [comment]
@thorsten-stripe Our use case is a pottery studio client whose primary revenue stream consists of monthly membership subscriptions. There is one membership tier, marketed to people unsure if a long term membership is what they want, which is a one-time purchase that provides "Passes" redeemable in the studio for limited trial access. This tier is never meant to be an ongoing subscription, instead, it should convert to a membership subscription if the member wishes to continue. 

The client does have a separate system for one-time payments, but this Pass item requires the same onboarding flow as their subscriptions, requiring liability waivers for example. It is also shown on the customer's profile in the membership management app. 

As long as the extension handles price.recurring.interval in the same manner between product creation and price creation/updates, I can build my workaround.

**Comment by thorsten-stripe** [comment]
@justin-elias thanks for outlining your use case.

Would you be able to expand a bit on the exact behaviour you're looking for regarding

> As long as the extension handles price.recurring.interval in the same manner between product creation and price creation/updates

For your use-case I'd recommend still using a recurring price and rather adding some metadata to your subscription: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#setting-metadata-on-the-subscription

You can then write your own cloud function to listen to the subscription document being created, you then check if it's a "one-time" purchase and then make and API request to Stripe to cancel the subscription at period end: https://stripe.com/docs/api/subscriptions/update#update_subscription-cancel_at_period_end

That way the "one-time" purchase use can still make use of the customer portal to upgrade their subscription rather than needing to create a new one.

**Comment by thorsten-stripe** [comment]
The following fix will roll out with the next release on Thursday PT:

[fix] - Corretly handle one-time (non-recurring) prices. This update adds a `type` parameter to the price document in Cloud Firestore:

```ts
/**
 * One of `one_time` or `recurring` depending on whether the price is for a one-time purchase or a recurring (subscription) purchase.
 */
type: "one_time" | "recurring";
```

This means that if you have both `one-time` and `recurring` prices on your Stripe account you will have to filter for `.collection('prices').where('type', '==', 'recurring') as one-time prices will error for the checkout session creation.
