### ISSUE TITLE
Support manual subscription creation via Stripe 

### ISSUE THREAD

**Issue by i14h** [stripe/stripe-firebase-extensions#187]
# Bug report

`firestore-stripe-subscriptions`

## Describe the bug

A developer reached out to Firebase who has a problem with a new customer not being added to the subscribers list on Firestore when he manually creates a subscription on Stripe. The customer is already in the Stripe Dashboard, they are registered in the system and they're just trying to add a subscription. All customers who checkout through the standard card payment process, get a subscription added to the Firestore. 

It seems that the webhook in Stripe extension only runs successfully if there is a pre-existing record of the subscription in Firestore - which there won't be if the subscription was created directly through Stripe.

Offending line is [here](https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/index.ts#L336)

**Comment by thorsten-stripe** [comment]
Creating subscriptions via the Stripe Dashboard works fine as long as the customer exists in the Cloud Firestore mapping collection:
![image](https://user-images.githubusercontent.com/23213994/118588749-9c1b1300-b7d1-11eb-8c92-c290fad2f58a.png)

In order to sync customers to Cloud Firestore via the extension, they will need to enable the "Sync" option in the extension configuration:
![image](https://user-images.githubusercontent.com/23213994/118588997-1481d400-b7d2-11eb-9da7-48e52265e4d2.png)

However, this only works for new users being signed up via Firebase. If either the user or the Stripe customer object existed before the extension was installed, the extension is not able to make this link, as it requires an authenticated context to do so. 

Normally that's fine, because when you create checkout sessions via the extension the user is authenticated and we just create a customer for them on the fly if we don't have a mapping yet. However if you're creating subscriptions in the Dashboard we are missing that authenticated context and can't create the mapping.

In that case, they will need to create the mapping doc in the customers collection manually:

```js
await admin
  .firestore()
  .collection("customers")
  .doc(uid) // the uid of the existing user in Firebase Auth
  .set({
    stripeId: "cus_123", // the customer ID of the existing customer in Stripe
  });
```

**Comment by huangjeff5** [comment]
I was wondering, what does "authenticated context" mean exactly? 

I noticed the webhook code inside the subscriptions extension already verifies the request is actually coming from Stripe using the webhook secret and request headers. 

Also based on the docs I read [here](https://stripe.com/docs/api/events/types#event_types-customer.subscription.created), it looks like the `subscription.created` event sends the `subscription` object (which includes `customer_id`) to the webhook. 

Doesn't that include all the information needed to generate the mapping?

**Comment by thorsten-stripe** [comment]
> Doesn't that include all the information needed to generate the mapping?

It does not. When generating the mapping we need to know that the user is authenticated (via Firebase authentication) and what their Firebase Auth UID is. This we only know when either a) the Firebase user is newly created as we can listen to `auth.user.created` event or b) when a Checkout Session is created, because that only works when the user is authenticated (based on Firebase rules in your application).
