### ISSUE TITLE
Delete Stripe customer by deleting Firestore customer file

### ISSUE THREAD

**Issue by JakeMalis** [stripe/stripe-firebase-extensions#3]
# Feature request

- `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

Yes. Firebase already has an extension that allows for data (besides the authentication account) to be removed upon account deletion.

## Describe the solution you'd like

If removing the customer file within Firestore would send a trigger to delete the customer on the dashboard, that would be the best solution.

## Additional context

https://firebase.google.com/products/extensions/delete-user-data

P.S. I'm so thankful for this extension. It really makes my life 400 thousand times easier. Keep up the phenomenal work!

**Comment by thorsten-stripe** [comment]
Thanks @JakeMalis for the kind words and the feature request :)

We're hoping to add this as a fast-follow. One important detail is: how do we handle active subscriptions for a user that is being deleted? E.g. would you want us to cancel all their active subscriptions and then delete their customer object?

Would love to hear your thoughts on that!

**Comment by rikelk** [comment]
Maybe something like the cleanUp function here:
https://github.com/firebase/functions-samples/blob/master/stripe/functions/index.js

/**
 * When a user deletes their account, clean up after them
 */
exports.cleanupUser = functions.auth.user().onDelete(async (user) => {
  const dbRef = admin.firestore().collection('stripe_customers');
  const customer = (await dbRef.doc(user.uid).get()).data();
  await stripe.customers.del(customer.customer_id);
  // Delete the customers payments & payment methods in firestore.
  const snapshot = await dbRef
    .doc(user.uid)
    .collection('payment_methods')
    .get();
  snapshot.forEach((snap) => snap.ref.delete());
  await dbRef.doc(user.uid).delete();
  return;
});

if i'm right a stripe delete customer automatically deletes customer subscriptions ?

**Comment by thorsten-stripe** [comment]
Thanks @rikelk. Yes, deleting a customer will cancel all their subscriptions. Yes, I'll add something along the lines. Will need to verify if this works together with the existing [Delete User Data extension](https://firebase.google.com/products/extensions/delete-user-data), that would be ideal.

**Comment by thorsten-stripe** [comment]
This has been added and should roll out with the next release on Thursday. Thanks again for your input! :)

**Comment by JakeMalis** [comment]
@thorsten-stripe If it cancelled the user subscription when deleting the account that would be amazing. Thank you so much, keep up the amazing stuff!

**Comment by jaytavares** [comment]
Hi all, I'm going to humbly suggest that this change be backed out. Deletion of customer objects in Stripe is irreversible! Well, at least through their public API--though apparently sometimes permanently 😓. It's handled on a case-by-case basis through Stripe Support. 

While yes, deletion of an Auth user would suggest a willingness to nuke data (there's no undoing the deletion of the user), there are scenarios where this may happen accidentally. I just added an issue 👆with one such example. We were migrating users from one Firebase project to another (as part of a monorepo reorganization). We had previously copied data from production into the new project for testing. The Stripe Firebase extension was enabled during the testing. On cut-over day, we cleared all data from the new Firebase project to have a clean slate to import all of the latest production data. The Auth users in the new project were not production yet, but they were connected to the live Stripe customers through the extension, and upon deletion all our live customers were deleted, all their payment methods were deleted, and all their subscriptions were cancelled.

Admittedly, I misstepped by not disabling the Stripe Firebase extension before beginning our cut over; however, that's kind of the point. Accidents happen in real life and it's our responsibility to enable fast recovery when they do. This feature is akin to foregoing database backups. Sure, you shouldn't delete data you still need, but what happens when you do?

For anyone who _needs_ this functionality (GDPR, perhaps?), it is easily added via a short and simple cloud function. If we're using customer deletion for its side-effect of cancelling subscriptions, then I think we should just be cancelling subscriptions. You can always reactivate subscriptions cancelled in error.

**Comment by jaytavares** [comment]
Correction: Cancelled subscriptions **cannot** be reactivated. 

Fortunately, Stripe Support was able to recover our deleted customers and their payment methods; however, there's no way to "un-cancel" all the subscriptions. So, we'll have to rebuild all of them from scratch. I think this confirms that automatic deletion of Stripe Customers is far too destructive an operation and shouldn't be the default behavior of this extension.
