### ISSUE TITLE
Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string. 

### ISSUE THREAD

**Issue by talalsiddiqui** [stripe/stripe-firebase-extensions#368]
# Bug report

- Extension name: [e.g. `firestore-stripe-payments`]

## Describe the bug

Function: ext-firestore-stripe-subscriptions-handleWebhookEvents
Type:  invoice.upcoming

I have noticed that on type [invoice. upcoming], document path is not a valid resource path error is coming. Please can anyone tell me is this from my side or it is genuine bug

**Comment by abierbaum** [comment]
@jsteele-stripe I am not the original poster of this bug, but I am seeing this exact issue coming up the last month or so after several months of no issues at all.  In my case I know the customersCollectionPath values is definitely set to a value and subscription creation and processing is working correctly.  I am seeing these errors though and would like to understand if there is something to worry about here.

**Comment by talalsiddiqui** [comment]
@jsteele-stripe All other invoice types such as paid, payment_succeeded, and payment_failed are working perfectly. The only issue is coming in [invoice. upcoming].

**Comment by jsteele-stripe** [comment]
@abierbaum @talalsiddiqui Are you able to provide some more detailed errors from your Firebase function logs?

**Comment by SmartManDeveloper** [comment]
@jsteele-stripe  Hi, same issue here. Probably caused by null  "payment_intent" for upcoming invoice. Detailed log -  [Error]: Webhook handler for  Stripe event [*] of type [invoice.upcoming] failed: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.

**Comment by noelmansour** [comment]
This is happening because the `invoice.upcoming` webhook event does not contain an `id` in the `object`. This results in an error on this line https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/functions/src/index.ts#L608

I'm not sure if this is a Stripe API issue. I'd imagine the `id` should be returned in the webhook event. The other `invoice.*` include it.

**Comment by brooksdra** [comment]
Okay, with the help of [noelmansour](https://github.com/noelmansour) comment:

> This is happening because the `invoice.upcoming` webhook event does not contain an `id` in the `object`. This results in an error on this line https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/functions/src/index.ts#L608
> 
> I'm not sure if this is a Stripe API issue. I'd imagine the `id` should be returned in the webhook event. The other `invoice.*` include it.
> 
> **Edit:** I played around with this some more. It seems the invoice doesn't actually exist when this webhook event is triggered. It only exists after the `invoice.created` event is triggered. The `id` won't be available until after that.
> 

I figured out the root cause of my problem. 

This is happening because the `invoice.paid` and `invoice.payment_succeeded` webhook events do not contain an `payment_intent` in the `object`. This results in an error on this line https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/functions/src/index.ts#L626

I was able to correct the issue by removing the trial period on a product price.

From this, I now have two new questions.
With a trial period, I only see the following webhook events, and the invoice-based events both fail:
```
invoice.paid
checkout.session.completed
customer.subscription.created
invoice.payment_succeeded
```
Without the trial period, I see the following set of webhook events, and all event work properly:
```
payment_intent.created
payment_intent.succeeded
checkout.session.completed
customer.subscription.created
customer.subscription.updated
invoice.paid
invoice.payment_succeeded
```

1) Is the first scenario acceptable, or is this clearly a problem?
2) I'm dubious about the order of events (top to bottom) as the broken `invoice.paid` comes before `customer.subscription. created`.

**Comment by vishishttiwari** [comment]
Having the same issue with invoice.payment_succeeded, invoice.paid and invoice.upcoming when a trial period is there. The exact errors are:

❗️[Error]: Webhook handler for  Stripe event [*] of type [invoice.payment_succeeded] failed: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.

❗️[Error]: Webhook handler for  Stripe event [*] of type [invoice.paid] failed: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.

❗️[Error]: Webhook handler for  Stripe event [*] of type [invoice.upcoming] failed: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.

I can also provide the event IDs if required. Thanks
