### ISSUE TITLE
Stripe One-Time Payment Extension

### ISSUE THREAD

**Issue by JakeMalis** [stripe/stripe-firebase-extensions#39]
# Feature request

## Describe the solution you'd like

I love the ease of use and functionality of the Stripe Subscriptions extension. I was hoping for the creation of another extension that allows for easier one-time payment processing. I love the design of https://github.com/stripe/stripe-payments-demo, but wish it would work with Firebase.

## Describe alternatives you've considered

[https://github.com/firebase/functions-samples/tree/master/stripe](https://github.com/firebase/functions-samples/tree/master/stripe) Also works, but it requires you to use Cloud Functions, rather than an extension; also, it uses the Stripe portal for checkout rather than the Stripe Card Element.

## Additional context

Keep up the amazing work! I understand if this feature is too much to ask.

**Comment by thorsten-stripe** [comment]
@JakeMalis would you mind outlining your use case? So far we've decided against a one-time payments extension because there are a lot of different very specific use cases for one-time payments, whereas subscriptions is a fairly standardized/predictable business model, where an extension is useful for many.

For the one-time payments use case, we generally recommend using https://github.com/firebase/functions-samples/tree/master/stripe because it allows you to modify the functions for your use case before deploying, something that isn't possible with extensions (at least atm).

But definitely would love to learn more about your use case which might help us reevaluate this!

**Comment by JakeMalis** [comment]
I plan on using it to collect money for tournament winners. I would like to collect money before allowing hosts to create tournaments.

**Comment by chetbox** [comment]
Hi! Thanks for this extension. We're evaluating it for software license purchasing and we think this could save us a lot of work. Our use case is purchasing a software license _and some hardware_ at a fixed cost. Together they make up our product and, in fact, the software is not much use without the hardware.

This extension allows customers to sign up for a subscription and buy our hardware products at the same time, but it does not allow users who have already bought a subscription to buy more hardware products from us at a later date.

Additionally one of our subscription levels is free. Should we add subscription with a zero cost to Stripe to support this? Given it's free we don't want users to have to "purchase" one through our site to start using it.

Given the functionality to purchase items alongside a subscription I think it's important to also support purchasing those items on their own.

**Comment by thorsten-stripe** [comment]
@chetbox thanks for outlining your use case! 

Having a zero cost pricing plan is legitimate and allows you to track a complete picture of subscribed users via the billing stats. One downside to it is that users will need to provide their payment details in Stripe Checkout, even for a zero cost pricing plan. If you don't want this, you could create a separate function to automatically subscribe them to your free plan like in this example: https://github.com/stripe-samples/netlify-stripe-subscriptions/blob/main/functions/identity-signup.js#L7-L14

The benefit of collecting the customer's payment details at the beginning is that you can then also create one-off payments for them: https://stripe.com/docs/payments/save-and-reuse#web-create-payment-intent-off-session, however I see that out of scope for this extension.

**Comment by chetbox** [comment]
Thanks @thorsten-stripe. We'll do some more experiments and try to work out how we can make the best experience for our users. We were hoping those on the free subscription wouldn't need to jump through any hoops to get up and running.

**Comment by thorsten-stripe** [comment]
Reopening this to prevent others from creating duplicates, and to collect more one-time payment use cases.

**Comment by dancixx** [comment]
It would be great for me and my company too. Our use case is that users have an option to buy single products in our store next to the monthly subscriptions.

**Comment by thorsten-stripe** [comment]
@dancixx why would you need an extension for that? For one time payments a simple cloud function should be enough: https://github.com/firebase/functions-samples/tree/master/stripe

**Comment by dancixx** [comment]
@thorsten-stripe you are right, but your subs extension works very well and would great to see same extension for one time payment. But if you wont support that i will solve on the way what you linked before. :)

**Comment by nikglavin** [comment]
Hey their thought I'd drop my use case in here as well:

I have a mix of subscriptions plans and a single "lifetime" deal that I would like to offer to early customers and ideally would like to process all payments through this extension.

Looking at the one of payment example above that looks like it goes through the tokenisation API, which I would prefer not to have do  as: 

- I don't want to store a payment token
- I prefer the UI used by the subscription extension and would like to have the checkout experience consistent rather than implement another UI for the embedded form.

Appreciate the consideration 👍

**Comment by thorsten-stripe** [comment]
One time payments are supported as of version 0.1.12: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/CHANGELOG.md#version-0112---2021-04-29

You can update the extension in your Firebase console to enable this.
