### ISSUE TITLE
Adding Subscription to User in Dashboard not updating Firestore

### ISSUE THREAD

**Issue by phillduffy** [stripe/stripe-firebase-extensions#43]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

Creating a Subscription in Stripe for a user does not send it back to Firestore

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1) User Sign up in Firebase
2) User is created as Customer in Firebase and as a Customer in Stripe
3) Add a Subscription to the user in Stripe Dashboard
4) Subscription is not added to the user in Firebase

## Expected behavior

Subscription should be added to the user's Firebase Document

**Comment by thorsten-stripe** [comment]
@phillduffy as it stands today the extension does not listen to `customer.subscription.created` as it expects the subscription to be created by the extension. So the subscription would only show up once the customer pays the invoice.

Would you mind expanding on your use case for creating the subscription in the dashboard rather than with Checkout? Feel free to [DM me](https://twitter.com/thorwebdev) if you can't/don't want to discuss in a public setting.

**Comment by thorsten-stripe** [comment]
@phillduffy were you able to get things set up after our DM chat?

I'm going to leave this issue open to see if others have a need for this, but for now I'm going to assume that subscriptions will be created via the extension rather than the Stripe Dashboard.

**Comment by Hadza** [comment]
> 
> 
> @phillduffy were you able to get things set up after our DM chat?
> 
> I'm going to leave this issue open to see if others have a need for this, but for now I'm going to assume that subscriptions will be created via the extension rather than the Stripe Dashboard.

Not exactly the same use case, I already have my webhooks written and I just want to try this integration to see if I can replace mine.

I use  a metered billing subscription, when someone signs up I create the stripe customer and subscribe him to my metered plan and proceed to record usage and after 1 month the invoice is created and I listen to webhook events to update the subscription acordingly.

I use my customer subscription status to handle their access to my web app, so, just on the tip of my head I can come up with two problems:

- If the subscription is created after an invoice is paid, how would I handle my users access? If I don't have the subscription status until they pay the invoice they could literally use my service forever as long as they don't pay ever
- If an invoice is not paid and the subscription gets deleted, if a user wants to get in again he has to pay the unpaid invoice and then I create a new metered subscription for my user, as I understand, that invoice won't trigger the creation of a subscription and won't let me update his subscription status

**Comment by thorsten-stripe** [comment]
@Hadza as it stands today, the extension does not support subscriptions created outside of the extension, only subscriptions that were created via the extension.

We could make the extension work for subscriptions created outside, by additionally listening to the `customer.subscription.created`, however I've been holding off on that because I want to figure out if it is actually needed.

In your case, you might be better off just replicating the webhook handler logic rather than using the extension.

**Comment by Hadza** [comment]
> 
> 
> @Hadza as it stands today, the extension does not support subscriptions created outside of the extension, only subscriptions that were created via the extension.
> 
> We could make the extension work for subscriptions created outside, by additionally listening to the `customer.subscription.created`, however I've been holding off on that because I want to figure out if it is actually needed.
> 
> In your case, you might be better off just replicating the webhook handler logic rather than using the extension.

Yeah, thats what I thought, still you guys gave me the idea to sync products and prices using webhooks, which is pretty cool, thanks!

**Comment by enricochionna** [comment]
Hello! I'm in a situation similar to Hadza's, but I need to create subscriptions with multiple products: a fixed recurring charge and a usage charge, both with the same billing interval. Since Checkout doesn't support metered billing, I have two options: (a) I use the Checkout, hence the extension, to create the subscription with only the fixed recurring charge, then implement my own function to listen to the `customer.subscription.created` webhook and update the subscription by adding the other price (metered plan); (b) or I could abandon the extension completely and use Stripe Elements to create a subscription with both prices in one tranche using my own function. Which way would you go? I guess if I use the extension I would still be able to have the subscription created automatically but then I would have to handle the usage on my own, right?

**Comment by thorsten-stripe** [comment]
@enricochionna thank for outlining your use case. 

Option (a) you outlined works fine and is pretty elegant in my opinion. I just tested this on my end (create subscription via checkout for monthly recurring, and then update the subscription to add the metered plan), and the update is correctly reflected in Cloud Firestore, so no concerns on that front. 

One thing to consider is that the billing portal currently does not support up/downgrading for subscriptions that include metered plans, so your customers would only be able view their billing history, update their payment methods, and cancel their subscription: 

![image](https://user-images.githubusercontent.com/23213994/92461922-67939800-f1fc-11ea-9a7b-09746e893fbc.png)

Option (b) would be significantly more work, so I'd go with your outlined option (a) 👍

**Comment by kkragoth** [comment]
My use case:

I need to have admin accounts on my live site with live payments that has subscription and obviously I don't want want him to pay using real credit card.

I created 100% off coupon but there's no way to have option for admin to enter this code in Stripe's checkout. (I'm using: ```stripe.redirectToCheckout({ sessionId });```)

The way I go about this is that I set up subscription with 100% off debug coupon in dashboard but then firebase has no idea that subscription was set up and shows subscription status inactive.

The only choice I'm left is to rewrite logic of subscription/admin but I'm working with managers that are non-programmers and I'd only want to give them access to stripe's dashboard and not necessarily leave them to mess with firebase's database everytime they want to invite someone to be admin.

**Comment by jaytavares** [comment]
I also have a need for the ability to recognize subscriptions made outside the extension. 

My use case: we have an extensive sales cycle that includes custom quoted invoices being sent to new clients. The subscriptions are created from within the Stripe dashboard and emailed to the client. When they pay their invoice, since the payment wasn't initiated through Checkout, no `checkout.session.completed` event is dispatched. Since the extension never receives notification of the subscription, the client cannot manage it through their customer portal through the Firebase app account.

**Comment by thorsten-stripe** [comment]
@kkragoth and @jaytavares thank you for adding your use cases. I'm planning to address this with the next release v. 0.1.7

**Comment by bcthakre** [comment]
Likewise. I can see customer created with web hook but Firestore collection has not been updated.

**Comment by Zuuai** [comment]
I create a dynamic payment link in my web app and the user signs up for the subscription. There were two customer records being created so I reconfigured the extension to solve this but no customer, subscription or product data is created so this would be really handy.
