### ISSUE TITLE
Make create stripe customer action configurable for use with document creation other than auth user.

### ISSUE THREAD

**Issue by leetworx** [stripe/stripe-firebase-extensions#51]
# Feature request

`firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

Currently, this extension will create a stripe customer for every firebase auth user associated with an app. In my case, not every app user is expected to be a paying user - and specifically, I already have the notion of an explicit 'customers' collection, which is a sub-set of auth users.

## Describe the solution you'd like

While defaulting to triggering on auth user creation is fine, it would be great if, perhaps during initial configuration, users of the extension could specify which collection should have it's doc create trigger associated with creating the stripe customer.

## Describe alternatives you've considered

Seems like the only real alternative for me here is to clone the bits of the webhooks etc, uninstall the extension, and rely on my own customer collection as the basis for my stripe integration.

## Additional context

Just wanted to say thanks - just starting out with stripe and this is an awesome resource, even if it's not a perfect fit for my use case just yet.

**Comment by thorsten-stripe** [comment]
Hey @leetworx, thanks for the kind words and for outlining your use case. 

We specifically set `merge:true` for inserting the Stripe customer record (https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/index.ts#L66) so that you can point it at an existing user collection without your existing customer data being overwritten.

We also do create a customer just in time when you create a checkout session, in case the user existed before the extension was installed: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/index.ts#L103-L108

So it should work if you just set your existing user collection as the path for the extension.

From your pov, what's the downside of having a customer record for each new user that signs up? Would that mess up your analytics somehow?

**Comment by leetworx** [comment]
Thanks very much for the response - from my perspective, the downside is really just that it doesn't align very well with the data model for my app, which I've tried to keep pretty clean. In my case, using firebase auth, I do explicitly have two 'classes' of records - 'users' (basically everyone who has signed in and actively engaged with the app) and 'customers' (those who are explicitly subscribing to the service as a 'provider' - note that consuming the service is free).

Perhaps you can clarify something for me (as I mentioned - I'm a complete noob with stripe) - how exactly is the 'checkout session that you mentioned established (I don't see where this particular cloud function would be triggered... is there an example by chance that uses this extension to demonstrate the full funtionality?)  - if the customer ID/info can be created lazily then perhaps it would serve both our use cases just to drop the customer creation triggered by auth.user create?

Thanks again for the additional details - looking forward to trying this out (btw - my app is a nuxt app, just in case there are any specific examples that might be more appropriate than others)

Cheers

**Comment by thorsten-stripe** [comment]
Yes, that might work. The checkout session creation is triggered when a new doc is added to the `checkout_sessions` sub-collection for a specific user: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#start-a-subscription-with-stripe-checkout

```js
const docRef = await db
  .collection('your/customerCollection/path')
  .doc(uid)
  .collection('checkout_sessions')
  .add({
    price: 'price_1GqIC8HYgolSBA35zoTTN2Zl',
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
```

If we can't find a customer ID in the user doc in the specified customer collection path we will create it on the fly and merge it into the customer doc. 

So the only thing you would have to do is to delete the `user.create` function after the extension has finished installing: 
![image](https://user-images.githubusercontent.com/23213994/91436667-25349780-e89b-11ea-817c-668aba675eea.png)

**Comment by leetworx** [comment]
Thanks very much for the suggestion (and apparently I missed the POSTINSTALL docs ;) - very helpful!)
I'm going to give this a try - the wrinkle I noticed however...
If I delete the 'user.create' function, I lose the ability to reconfigure the extension (appears to fail some form of validation).
For example - deleting the function before I update the signing secret (like I just did) appears to be a dead-end...

If leaving the user.create function in place, is there a way to specify it as 'optional' for the extension so as to permit reconfiguration/validation?

Thanks again

**Comment by leetworx** [comment]
One additional question Thor - 

seeing that the 'customer collection' appears to have the form:

/customer_collection/auth_uid/checkout_sessions...
(where auth_uid == the user ID derived directly from the generate firebase auth ID)

Is there any issue with having the auto-generated doc IDs for the customer_collection NOT correspond directly to a user auth_id? (i.e. when creating a portal link etc, or redirecting to checkout - is it presumed that we're providing an authenticated UID for use in signing into stripe etc? (or or the two systems essentially completely independent, in which case the firebase auth ID for the current actual user is not required for the checkout and/or portal?

(hope this is clear...)

Thanks
T

**Comment by thorsten-stripe** [comment]
> If I delete the 'user.create' function, I lose the ability to reconfigure the extension (appears to fail some form of validation).

Ah that's a bummer, then the approach with deleting the function won't work.

> Is there any issue with having the auto-generated doc IDs for the customer_collection NOT correspond directly to a user auth_id? (i.e. when creating a portal link etc, or redirecting to checkout - is it presumed that we're providing an authenticated UID for use in signing into stripe etc? (or or the two systems essentially completely independent, in which case the firebase auth ID for the current actual user is not required for the checkout and/or portal?

Before creating a checkout session or a portal link we will need to make sure that they are authenticated and therefore are allowed to access the customer portal. That's why the doc ID needs to be the UID of the user. It's also used in the Cloud Firestore security rules to make sure each customer can only read their own details.

> If leaving the user.create function in place, is there a way to specify it as 'optional' for the extension so as to permit reconfiguration/validation?

Not at the moment, this will require changes to the extension. I can look into this later this week, but for the time being it sounds like you might be better off to maybe replicate the relevant functions in your project as you seem to have a fairly specific information architecture.

**Comment by leetworx** [comment]
Thanks very much for the additional details - greatly appreciated! With this I was able to successfully integrate the logic for the subscription extension into my workflow (relying on lazy customer collection update upon checkout session creation and associating the stripe ID with my customer ID, while ensuring that the 'admin' user is authenticated prior to accessing the portal). The webhooks are awesome btw - thanks again! Feel free to close this if you like.

**Comment by thorsten-stripe** [comment]
Brilliant, glad you got it working :)

**Comment by ajbarry** [comment]
@thorsten-stripe first of all let me echo @leetworx thanks for creating this extension ... this is by far the easiest "real" stripe integration I have worked on.

I came here looking for a way to backfill stripe customer ids on my existing users but I understand from your comments this may not be necessary if one is lazily created along with a checkout session. Nice. This detail would make a great addition to the extension docs.

I'd like to make the case for lazy customer creation to be the default behavior. We are using this extension in a multi-tenant SaaS where one user, say an admin or billing contact, is responsible for purchasing a subscription on behalf the tenant, for all users. We think of the tenant as our "customer" rather than an individual user. As it is now, every user regardless of the tenant is registered as a stripe customer with only a very small subset expected to ever purchase a subscription. At this point it is a mere inconvenience when viewing the customer list within stripe but your comment regarding the pollution of analytics does give me pause to fully consider the downstream effects of this side-effect. I wonder what long-term impacts this might have on sales-ops and support within stripe. I'm not sure if I will go off-the-rails and delete the `user_create` function as you offered but I would definitely exercise the option to disable this function if it were available and lazy customer creation continued function.

In the meantime, maybe I could ask what motivations went into the eager 1:1 user to customer creation? Is there some pre-purchase flow or lead tracking features that stripe intends us to employ? Anything we've yet to consider in this regard?

Regardless of the outcome for us, this extension has already saved us countless hours on the integration so a huge thank you from our team to yours!

**Comment by thorsten-stripe** [comment]
Thanks for the kind words @ajbarry!

That's a good point, IIRC the main motivation was to make the extension easy to use for folks who aren't experienced with Firebase, and therefore create the customer doc for them when a new user signs up, but it sounds like most people already do this themselves in their integrations, so that's a good point. 

I will look into making user <> customer sync optional.
