### ISSUE TITLE
createCheckoutSession function very slow

### ISSUE THREAD

**Issue by JakeMalis** [stripe/stripe-firebase-extensions#68]
# Bug report

- `firestore-stripe-subscriptions`

## Describe the bug

When clicking on the button in my app that should take the user to the Stripe checkout page, it takes anywhere from 500-5000 ms to redirect the user. Most of the time it takes for the user to be redirected is from the time it takes the createCheckoutSession to run. As well, the function can have up to 6 seconds of latency according to Firebase logger.

## Expected behavior

I wish the program ran way faster.

## Screenshots
![Screenshot 2020-09-22 113131](https://user-images.githubusercontent.com/18268912/93903920-3cfb1200-fcc7-11ea-8198-d27f85cb3bd9.png)
![Screenshot 2020-09-22 113018](https://user-images.githubusercontent.com/18268912/93903923-3d93a880-fcc7-11ea-8569-f18dcb885b57.png)
![Screenshot 2020-09-22 113258](https://user-images.githubusercontent.com/18268912/93904037-61ef8500-fcc7-11ea-8dbd-57b4df0729e5.png)

## System information

- OS: Windows 10
- Browser: Microsoft Edge (tested on all browsers)

**Comment by thorsten-stripe** [comment]
@jhuleatt @rosariopfernandes any idea how to speed this up? Is there any way to keep functions warm?

Or would making it a callable function instead of a `doc.created` trigger faster potentially?

**Comment by JakeMalis** [comment]
Would there be an easier way to get the URL to the checkout session without using the Firebase function? Functions are great for things that aren't instant in my experience, but hyperlinks should be instantaneous.

**Comment by thorsten-stripe** [comment]
@JakeMalis there is not, the Checkout sessions needs to be created in a server-side environment.

**Comment by rosariopfernandes** [comment]
@thorsten-stripe I don't think there's a way to keep functions warm at the moment.


@JakeMalis Can you provide more information to help us debug:
1. Which location did you choose for Cloud Functions when you setup the extension?
1. Which location are you using for the Cloud Firestore data?

It's common to face higher latency when these 2 don't match, as explained [here](https://firebase.google.com/docs/functions/locations#selecting-regions_firestore-storage).

**Comment by JakeMalis** [comment]
My Functions and Firestore are hosted at US-east1.

**Comment by jhuleatt** [comment]
It looks like you're testing with a very low number of invocations/second. At this low load, a number of these responses are probably "cold starts", since Cloud Functions scales down to zero when it doesn't experience any load. As you get more traffic, Cloud Functions will keep function instances "warm" and they should be *much* faster.

@thorsten-stripe there are ways to optimize to reduce cold start time ([explained here](https://firebase.google.com/docs/functions/tips)) that may be worth looking into.

**Comment by JakeMalis** [comment]
Ok, so when I release the Stripe functionality to my app (expecting 35,000 users), it should run significantly faster?

**Comment by jhuleatt** [comment]
Essentially, yes. For a deep dive on the "why", check out [this video](https://www.youtube.com/watch?v=v3eG9xpzNXM). It was created to teach Cloud Functions for Firebase developers how to reduce cold start times, but in doing so it does a good job explaining why they happen.

Number of cold starts also depends on the shape of the traffic your functions get - if your traffic is smooth (say, a consistent 100QPS), almost every request will hit a "warm" function. However, if your traffic is spiky (1QPS, then 1000 QPS, then down to 5 QPS, up to 50, down to 1), Cloud Functions will have to continually adjust the number of instances running, resulting in a lot of cold starts.

**Comment by JakeMalis** [comment]
Sounds good to me! I'll release the Stripe functionality to the beta and try to see if I can confirm the delay is due to cold starts. Thanks!

**Comment by cvoadmin** [comment]
@Benjamin-Lee Even with multiple instances I found latency stayed the same. I think high QPS is all that matters.
I use a back blocker to prevent lost conversions.
```
history.pushState(null, null, location.href);
window.onpopstate = function () {
  history.go(1);
};
```

**Comment by studio-clinic** [comment]
Has there been any progress forward on this?

I'm seeing 7000ms between button click and redirecting to Stripe checkout page.

`const docRef = await addDoc(
      collection(db, `customers/${user.uid}/checkout_sessions`),
      {
        price: price,
        success_url: window.location.origin,
        cancel_url: window.location.origin,
      }
    );
    onSnapshot(docRef, (snap) => {
      const { error, url } = snap.data();
      if (url) {
        window.location.assign(url);
        setLoading(false);
      }
      if (error) {
        console.log("error >>>>>>>>>>>", error.message);
        setLoading(false);
      }
    });`

**Comment by i14h** [comment]
Can you all who are seeing an increased latency open a support ticket with Cloud (GCF specifically) and mention this issue? Each case might need a different resolution and the support team can help you there. I'm not sure if this is Stripe related or GCF related but we can help identify that with a better analysis.

**Comment by cvoadmin** [comment]
That'll be $30.

**Comment by willbattel** [comment]
For anyone trying to diagnose this, I'm pretty sure this all boils down to the same issue that has long plagued Cloud Functions. Cold start times are ridiculously long, not at all suitable for production, and Google has been aware and unable to fix for over two years now. Minimum instances somewhat mitigates the issue but it's merely a bandaid that doesn't actually fix the problem because cold starts are unavoidable in practice, no matter how consistent your traffic is.

https://issuetracker.google.com/issues/158014637

One thing that we have seen recommended and implemented for our own functions that does seem to make a noticeable improvement, is to raise the memory allocation from the default 256 MB to 1 GB or more. The memory itself doesn't make any difference but the CPU scheduling Google uses under the hood is dependent on the memory configuration. The default 256 MB grants your function 400 MHz CPU cycles. whereas 1 GB gets you 1.4 GHz, 2GB 2.4 GHz, and 4GB 4.8 GHz. These higher CPU clock speeds noticeably reduce our cold start times. It's still not ideal but it's a big help not well documented by Google.

https://firebase.google.com/docs/functions/manage-functions#set_timeout_and_memory_allocation
