### ISSUE TITLE
Remove 'stripeRole' when deleting a user subscription

### ISSUE THREAD

**Issue by CaptainYouz** [stripe/stripe-firebase-extensions#75]
# Feature request

`firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

When deleting a user subscription in the `customers` collection (to cancel it) (directly from Firebase admin panel), it does not change the custom claim role `stripeRole` on the user token.

Edit: when deleting the subscriptions from Stripe dashboard, it also remove the `stripeRole` custom role.

## Describe the solution you'd like

When deleting a user subscription in the `customers` collection, delete the custom claim role `stripeRole`.

## Describe alternatives you've considered

Create manually a cloud function to delete the subscription in the `customers` collection and in the same time, removing the `stripeRole` custom claim role, or use stripe api to cancel the subscription.

**Comment by thorsten-stripe** [comment]
The source of truth for Subscriptions is your Stripe account. In order to cancel a Subscription, you need to either cancel it via the Stripe Dashboard, API, or the customer portal. Deleting a subscription doc in Firestore won't have any effect on the Subscription in Stripe and is therefore not advisable. 

Feel free to expand on your use case and reopen the issue if you feel it's something others might want as well.
