### ISSUE TITLE
 The checkout form has the wrong email when user changes his email before

### ISSUE THREAD

**Issue by Arystosedes** [stripe/stripe-firebase-extensions#76]
# Bug report

- Extension name: [e.g. `firestore-stripe-subscriptions`]

## Describe the bug

Wrong/bad user email when he changes his email address before subscribing to some plan. The checkout form has the wrong email then. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Sign up a new user in service which uses Firebase
2. New customer (stripe) is created - with an email address which user put in the register form
3. User doesn't subscribe to a plan yet but changes his email address in service which uses Firebase
4. User subscribe to a plan, with old/bad email

## Expected behavior

Users can change his email address, it's typical behavior. So the checkout form should have access to his updated (last used) email address.

**Comment by thorsten-stripe** [comment]
The customer is able to update their email in the Checkout form.

Also, I'm currently working on a solution for #66 which will change the default behaviour to creating the customer on the fly when the checkout session is being created, instead of when they sign up. This will also resolve this issue.

**Comment by radley** [comment]
> The customer is able to update their email in the Checkout form.

No, we can't.
