### ISSUE TITLE
Hardcode price for Stripe Subscription

### ISSUE THREAD

**Issue by JakeMalis** [stripe/stripe-firebase-extensions#9]
# Feature request

- `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.
When running the code shown below, it throws an error because `formData.get('price')` is not setup for my website. How could I hardcode in the price for the product. Let's say that the price is $5.00 USD, how do I set that.

`const docRef = await db
  .collection('customers')
  .doc(currentUser.uid)
  .collection('checkout_sessions')
  .add({
    price: formData.get('price'),
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
// Wait for the CheckoutSession to get attached by the extension
docRef.onSnapshot((snap) => {
  const { sessionId } = snap.data();
  if (sessionId) {
    // We have a session, let's redirect to Checkout
    // Init Stripe
    const stripe = Stripe('pk_test_1234');
    stripe.redirectToCheckout({ sessionId });
  }
});`

## Describe the solution you'd like

I want to hard code in the price of the product that I'm purchasing.

## Additional context
This is the error thrown when I type 500 as my price.
`❗️[Error]: Checkout session creation failed for doc [aiBdCNtUt0uIKuLpOuVk]: No such price: 500 `

P.S. thank you so much for your delete customer feature. It is a game changer. Keep up the fantastic work!

**Comment by thorsten-stripe** [comment]
Hey @JakeMalis, you can't set the pricing data on the client side as it could be tampered with. E.g. someone could open the browser dev tools and simply change the pricing to be lower.

That's why you need to create the pricing details in Stripe first: https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/POSTINSTALL.md#create-product-and-pricing-information

You can then initiate the checkout with the price ID from Stripe:

```js
const docRef = await db
  .collection('customers')
  .doc(currentUser.uid)
  .collection('checkout_sessions')
  .add({
    price: 'price_1GqIC8HYgolSBA35zoTTN2Zl', // price ID from Stripe created in first step
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });
// Wait for the CheckoutSession to get attached by the extension
docRef.onSnapshot((snap) => {
  const { sessionId } = snap.data();
  if (sessionId) {
    // We have a session, let's redirect to Checkout
    // Init Stripe
    const stripe = Stripe('pk_test_1234');
    stripe.redirectToCheckout({ sessionId });
  }
});
```

I'll update the `price: formData.get('price'),` to `price: 'price_1GqIC8HYgolSBA35zoTTN2Zl',` in the POSTINSTALL to make that clearer. Thanks for flagging!
